### ISSUE TITLE
Make herbs farmable

### ISSUE THREAD

**Issue by 0xfrej** [Lai0n/Wiedzminstvo#15]
possibly in a way that after some time the flower will spread to nearby block

This will work somewhat like this: Plant a flower - > fertilize it -> the plant will spread for N number of ticks -> stops spreading

Fertilizer item name: "Bone meal paste"
recipe: ( fifth essence + alchemy paste -> healing paste ) + bone meal ->  bone meal paste

**Comment by Lai0n** [comment]
Instead of farming..lets make system like this...when you destroy the flower you will get herb itself but if you trim it...it can regrow after some time but when you use the paste it will regrow faster and the cycle continues...from trimmed flower itself you can grow it again using pot or something...somehow make a plant out of it

**Comment by Lai0n** [comment]
Also not all flowers should be doable this way. Small flowers like arenaria and bison grass should be unfarmable...or maybe later add some system like on top
